version: '3'

services:
  aws-insights:
    image: steampipe-aws-insights
    container_name: steampipe-aws-insights
    build:
      context: .
      dockerfile: Dockerfile.aws-insights
    command: ["steampipe", "service", "start", "--foreground", "--dashboard", "--dashboard-listen=network"]
    restart: unless-stopped
    ports:
      - 9193:9193
      - 9194:9194
    environment:
      - STEAMPIPE_DATABASE_PASSWORD=steampipe
      - STEAMPIPE_CACHE=true
      - STEAMPIPE_CACHE_MAX_SIZE_MB=4096
      - STEAMPIPE_CACHE_TTL=300
      - STEAMPIPE_QUERY_TIMEOUT=120
      - STEAMPIPE_MAX_PARALLEL=10
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
  aws-compliance:
    image: steampipe-aws-compliance
    container_name: steampipe-aws-compliance
    build:
      context: .
      dockerfile: Dockerfile.aws-compliance
    command: ["steampipe", "service", "start", "--foreground", "--dashboard", "--dashboard-listen=network"]
    restart: unless-stopped
    ports:
      - 9195:9193
      - 9196:9194
    environment:
      - STEAMPIPE_DATABASE_PASSWORD=steampipe
      - STEAMPIPE_CACHE=true
      - STEAMPIPE_CACHE_MAX_SIZE_MB=4096
      - STEAMPIPE_CACHE_TTL=300
      - STEAMPIPE_QUERY_TIMEOUT=120
      - STEAMPIPE_MAX_PARALLEL=10
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
  metabase-dashboard:
    image: metabase/metabase
    container_name: metabase
    restart: unless-stopped
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
